name: Deploy to Azure App Service

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout code!
      uses: actions/checkout@v3

    - name: 🐍 Set up Python thon
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 📦 Install dependencies
      run: pip install -r requirements.txt

    - name: ✅ Ensure startup.sh is executable
      run: chmod +x startup.sh

    - name: 📁 Create deployment package
      run: zip -r app.zip . -x "*.git*" "*.github*" "app.zip"

    - name: 🔑 Azure Login
      uses: azure/login@v1
      with:
      creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 🚀 Deploy to Azure Web App (Linux)
      run: |
      az webapp deploy \
        --name ghibli-style-app \
        --resource-group ghibli-style-app_group \
        --src-path app.zip \
        --type zip


    - name: 🧪 Afficher le contenu HTML retourné
      run: |
        sleep 30
        echo "🔍 Contenu HTML retourné par l'app :"
        curl -s https://ghibli-style-app-csbqbeefd3aueqgb.francecentral-01.azurewebsites.net
